# server configuration
server:
  port: 8051

#spring database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ProductTestDB
    username: postgres
    password: 12345

  # spring jpa configuration
  jpa:
    database: postgresql
    hibernate:
    ddl-auto: update
    show-sql: true

